### ISSUE TITLE
How to get the visible SAM memory consume

### ISSUE THREAD

**Issue by ZHANG-SH97** [pytorch-labs/segment-anything-fast#107]
hi, 
After reading the documentation, I found this picture very interesting, but I did not find a way to draw or generate this image. How can I obtain such an image?
![image](https://github.com/pytorch-labs/segment-anything-fast/assets/92924119/cb990e03-a7e8-4250-944d-54c2fd14ca69)
Looking forward to your answer :)

**Comment by cpuhrsch** [comment]
Hello @ZHANG-SH97,

You may find the following snippets useful: https://github.com/pytorch-labs/segment-anything-fast/blob/main/experiments/README.md#memory-profiles

Thank you!

**Comment by ZHANG-SH97** [comment]
thanks
