### ISSUE TITLE
Labeling tool ISAT have supported segment-anything-fast.

### ISSUE THREAD

**Issue by yatengLG** [pytorch-labs/segment-anything-fast#79]
Labeling tool [ISAT](https://github.com/yatengLG/ISAT_with_segment_anything) have supported [segment-anything-fast](https://github.com/pytorch-labs/segment-anything-fast).

The effect is very amazing ,time cost from 0.8198s to 0.2228s and GPU memory from 7300M to 4900M when use sam_vit_h_4b8939.pth.

This method can be used on ohter SAM type model? Like [sam-hq](https://github.com/SysCV/sam-hq), [MobileSAM](https://github.com/ChaoningZhang/MobileSAM).

**Comment by msaroufim** [comment]
That's fantastic news! Indeed the techniques are all generic and should work over arbitrary PyTorch models, we won't have the bandwidth to write our own implementations but if you'd like to write your own we'd be happy to assist

**Comment by yatengLG** [comment]
Thanks, i will try it.

O(∩_∩)O
