### ISSUE TITLE
Compatible with torch.export?

### ISSUE THREAD

**Issue by dbbert** [pytorch-labs/segment-anything-fast#81]
Is this implementation compatible with [torch.export](https://pytorch.org/docs/stable/export.html)? I want to deploy SAM in a serverless fashion but the compile step causes long cold start times.

**Comment by msaroufim** [comment]
The model has 0 graph breaks so indeed torch.export should work, if you run into any issues please let us know!

**Comment by cpuhrsch** [comment]
@dbbert I'm going to close this now since the issue seems to be resolved, but please reopen if that's not the case.
