### ISSUE TITLE
Inference on A10 GPU become slower than original SAM

### ISSUE THREAD

**Issue by GovernorHo** [pytorch-labs/segment-anything-fast#86]
Hi, I run inference on Nvidia A10 GPU using sam_model_fast_registry to init model and SamAutomaticMaskGenerator to generate masks, but the inference time become slower than original SAM. Why?

original SAM elapsed time: 6.36s per image.
SAM-fast elapsed time: 10.92s per image.

**Comment by cpuhrsch** [comment]
Hello @GovernorHo - Thank you for opening this issue. This is very similar to https://github.com/pytorch-labs/segment-anything-fast/issues/76 . I'll close this issue to keep the number of similar issues low, but please reopen if you don't think this applies to your ask.
